[package]
name = "tilt_thing"
version = "0.1.0"
authors = ["Markus Røyset <maroider@protonmail.com>"]
edition = "2018"

[dependencies]
serialport = "3.3.0"
monman = { git = "https://github.com/maroider/monman" }
